wrn50_2:
 full_name: wide_resnet50_2
 ckp_path: wrn50_2/wrn50_2.pth

wrn101_2:
 full_name: wide_resnet101_2
 ckp_path: wrn101_2/wrn101_2.pth

resnet18:
 full_name: resnet18
 ckp_path: resnet18/resnet18.pth

resnet34:
 full_name: resnet34
 ckp_path: resnet34/resnet34.pth

resnet50:
 full_name: resnet50
 ckp_path: resnet50/resnet50.pth

inc_v3:
 full_name: inception_v3
 ckp_path: inc_v3/inc_v3.pth

inc_v4:
 full_name: inception_v4
 ckp_path: inc_v4/inc_v4.pth

bit50_1:
 full_name: resnetv2_50x1_bitm
 ckp_path: bit50_1/bit50_1.pth

bit101_1:
 full_name: resnetv2_101x1_bitm
 ckp_path: bit101_1/bit101_1.pth

vit_b:
 full_name: vit_base_patch16_224
 ckp_path: vit_b/vit_b.pth

vit_s:
 full_name: vit_small_patch16_224
 ckp_path: vit_s/vit_s.pth

vit_t:
 full_name: vit_tiny_patch16_224
 ckp_path: vit_t/vit_t.pth

deit_b:
 full_name: deit_base_patch16_224
 ckp_path: deit_b/deit_b.pth

deit_s:
 full_name: deit_small_patch16_224
 ckp_path: deit_s/deit_s.pth

deit_t:
 full_name: deit_tiny_patch16_224
 ckp_path: deit_t/deit_t.pth

swin_b:
 full_name: swin_base_patch4_window7_224
 ckp_path: swin_b/swin_b.pth

swin_s:
 full_name: swin_small_patch4_window7_224
 ckp_path: swin_s/swin_s.pth

swin_t:
 full_name: swin_tiny_patch4_window7_224
 ckp_path: swin_t/swin_t.pth

incres_v2:
  full_name: 'inception_resnet_v2'
  ckp_path: 'incres_v2/incres_v2.pth'

resnet101:
  full_name: 'resnet101'
  ckp_path: 'resnet101/resnet101.pth'

inc_v3_ens3:
  full_name: 'adv_inception_v3_ens3'
  ckp_path: 'ens3_adv_inception_v3/ens3_adv_inception_v3.ckpt'

inc_v3_ens4:
  full_name: 'adv_inception_v3_ens4'
  ckp_path: 'ens4_adv_inception_v3/ens4_adv_inception_v3.ckpt'

incres_v2_ens:
  full_name: 'adv_inception_resnet_v2_ens'
  ckp_path: 'ens_adv_inception_resnet_v2/ens_adv_inception_resnet_v2.ckpt'
